version: "3.7"
services:
  database:
    image: amsterdam/postgres11
    ports:
      - "5415:5432"
    environment:
      POSTGRES_DB: dataservices
      POSTGRES_USER: dataservices
      POSTGRES_PASSWORD: insecure
    volumes:
      - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"
      - .:/host
    extra_hosts:
      admin.data.amsterdam.nl: 10.243.16.4
  web:
    build:
      context: src/
      args:
        PIP_REQUIREMENTS: requirements_dev.txt
    ports:
      - "8000:8000"
    links:
      - database

    environment:
      UWSGI_HTTP_SOCKET: ":8000"
      UWSGI_MODULE: "dso_api.wsgi"
      UWSGI_CALLABLE: "application"
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/dso_api/static=/static"
      SECRET_KEY: insecure
      DATABASE_URL: "postgres://dataservices:insecure@database/dataservices"
      DJANGO_DEBUG: 1
    volumes:
      - ./src:/app
      - ./docs/build/html:/docs-static
    command: uwsgi --py-auto-reload=1
