apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dso-namespace
  name: database-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
status: {}
