apiVersion: v1
kind: Service
metadata:
  namespace: dso-namespace
  labels:
    team: datapunt
    networking/namespace: dso
  name: database
spec:
  ports:
    - name: "postgres"
      port: 5432
      targetPort: 5432
  selector:
    team: datapunt
    networking/namespace: dso
status:
  loadBalancer: {}
