apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dso-namespace
  labels:
    team: datapunt
    networking/namespace: dso
    type: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      type: database
      networking/namespace: dso
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        team: datapunt
        networking/namespace: dso
        type: database
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: dataservices
            - name: POSTGRES_PASSWORD
              value: insecure
            - name: POSTGRES_USER
              value: dataservices
          image: amsterdam/postgres11
          name: database
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /root/.ssh/datapunt.key
              name: database-claim0
            - mountPath: /host
              name: database-claim1
      restartPolicy: Always
      volumes:
        - name: database-claim0
          persistentVolumeClaim:
            claimName: database-claim0
        - name: database-claim1
          persistentVolumeClaim:
            claimName: database-claim1
status: {}
