apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dso-namespace
  labels:
    team: datapunt
    networking/namespace: dso
    api: dso
  name: dso-api
spec:
  replicas: 1
  selector:
    matchLabels:
      api: dso
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        networking/namespace: dso
        team: datapunt
        api: dso
    spec:
      containers:
        - args:
            - uwsgi
            - --py-auto-reload=1
          env:
            - name: DATABASE_URL
              value: postgres://dataservices:insecure@database/dataservices
            - name: DJANGO_DEBUG
              value: "0"
            - name: SECRET_KEY
              value: insecure
            - name: UWSGI_CALLABLE
              value: application
            - name: UWSGI_HTTP_SOCKET
              value: :8000
            - name: UWSGI_MASTER
              value: "1"
            - name: UWSGI_MODULE
              value: dso_api.wsgi
            - name: UWSGI_STATIC_MAP
              value: /dso_api/static=/static
          image: dso-api
          imagePullPolicy: Never
          name: dso-api
          ports:
            - containerPort: 8000
          resources: {}

      restartPolicy: Always

status: {}
