apiVersion: v1
kind: Service
metadata:
  namespace: sociaal-namespace
  labels:
    team: datateam-sociaal
    api: sociaal
    networking/namespace: sociaal
  name: sociaal
spec:
  type: ClusterIP
  ports:
    - name: "sociaal"
      port: 8888
      targetPort: 8888

  selector:
    api: sociaal
    networking/namespace: sociaal
